/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DigitalInviteRouteImport } from './routes/digital-invite'
import { Route as PhysicalCardsRouteImport } from './routes/physical-cards'
import { Route as StationeryRouteImport } from './routes/stationery'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalInviteRoute = DigitalInviteRouteImport.update({
  id: '/digital-invite',
  path: '/digital-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysicalCardsRoute = PhysicalCardsRouteImport.update({
  id: '/physical-cards',
  path: '/physical-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const StationeryRoute = StationeryRouteImport.update({
  id: '/stationery',
  path: '/stationery',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/digital-invite': typeof DigitalInviteRoute
  '/physical-cards': typeof PhysicalCardsRoute
  '/stationery': typeof StationeryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/digital-invite': typeof DigitalInviteRoute
  '/physical-cards': typeof PhysicalCardsRoute
  '/stationery': typeof StationeryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/digital-invite': typeof DigitalInviteRoute
  '/physical-cards': typeof PhysicalCardsRoute
  '/stationery': typeof StationeryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/digital-invite' | '/physical-cards' | '/stationery'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/digital-invite' | '/physical-cards' | '/stationery'
  id: '__root__' | '/' | '/digital-invite' | '/physical-cards' | '/stationery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DigitalInviteRoute: typeof DigitalInviteRoute
  PhysicalCardsRoute: typeof PhysicalCardsRoute
  StationeryRoute: typeof StationeryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-invite': {
      id: '/digital-invite'
      path: '/digital-invite'
      fullPath: '/digital-invite'
      preLoaderRoute: typeof DigitalInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physical-cards': {
      id: '/physical-cards'
      path: '/physical-cards'
      fullPath: '/physical-cards'
      preLoaderRoute: typeof PhysicalCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stationery': {
      id: '/stationery'
      path: '/stationery'
      fullPath: '/stationery'
      preLoaderRoute: typeof StationeryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DigitalInviteRoute: DigitalInviteRoute,
  PhysicalCardsRoute: PhysicalCardsRoute,
  StationeryRoute: StationeryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
